steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'beta'
    - 'run'
    - 'jobs'
    - 'update'
    - '$_JOB_NAME'
    - '--region'
    - '$_REGION'
    - '--update-env-vars'
    - 'SLACK_WEBHOOK_URL=$_SLACK_WEBHOOK_URL'
    - '--update-env-vars'
    - 'GCP_BIGQUERY_DATASET=$_GCP_BIGQUERY_DATASET'
    - '--update-env-vars'
    - 'GCP_BIGQUERY_TABLE=$_GCP_BIGQUERY_TABLE'
    - '--update-env-vars'
    - 'GCS_BUCKET_NAME=$_GCS_BUCKET_NAME'
substitutions:
  _IMAGE_NAME: new-books-notification
  _JOB_NAME: new-books-notification
  _REGION: asia-northeast1
  _SLACK_WEBHOOK_URL: ""
  _GCP_BIGQUERY_DATASET: new_books_notification
  _GCP_BIGQUERY_TABLE: new-books
  _GCS_BUCKET_NAME: new-books-notification
options:
  substitution_option: 'ALLOW_LOOSE'
